version: "3"
services:
  db:
    build:
      context: ../Database
      dockerfile: Dockerfile.mysql
    container_name: container-banco-GrafWall
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: HNj74PYaX7
      MYSQL_DATABASE: banco-grafwall-mysql
      MYSQL_USER: supervisor
      MYSQL_PASSWORD: jysOS9o8lB
    networks:
      - mynetwork

  api:
    build:
      context: ../graf-wall-api
      dockerfile: Dockerfile
    container_name: container-api-GrafWall
    ports:
      - "3000:3000" # Para acessar a API localmente
    networks:
      - mynetwork
    command: /bin/sh -c "npm run start:dev"
    volumes:
      - ../graf-wall-api:/app

networks:
  mynetwork:
    driver: bridge
